baseURL = 'https://shiriev.ru/'
languageCode = 'en-us'
title = 'Artur Shiriev'
theme = 'hugo-blog-awesome'

[params]
sitename = "Artur's Blog"
defaultColor = "auto"
description = "Artur Shiriev - teamlead, techlead at Raiffeisen. Full Stack Web Developer with 13+ years of experience. Python, TypeScript, devops."
mainSections = ['posts']
toc = false
goToTop = true

[params.author]
intro = "Artur Shiriev"
name = "Artur Shiriev"
description = "Teamlead, techlead at Raiffeisen. Full Stack Web Developer with 13+ years of experience. Python, TypeScript, devops"

[menu]
[[menu.main]]
pageRef="/"
name = 'Home'
url = '/'
weight = 10
[[menu.main]]
pageRef="posts"
name = 'Posts'
url = '/posts/'
weight = 20
[[menu.main]]
pageRef="about"
name = 'About'
url = '/about/'
weight = 30

[[params.socialIcons]]
name = "github"
url = "https://github.com/lesnik512/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/artur-shiriev/"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/modern_python"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/4794759/artur-shiriev"

[[params.socialIcons]]
name = "email"
url = "mailto:me@shiriev.ru"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.twitter]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true
